require 'rails_helper'
require Rails.root.join 'lib/assets/mail/mail_parsers/ms_isac_blacklist_parser'

RSpec.describe MsIsacBlacklistParser do
  before :all do
    @blacklist = File.read Rails.root.join 'spec/fixtures/ms_isac_blacklist.html'
  end

  context '#parse(str)' do
    before :all do
      @obj = MsIsacBlacklistParser.new
      @obj.parse @blacklist
    end

    it 'places all the domains in an array inside @domains' do
      expect(@obj.domains).to match_array(%w(
                                      regeneration-data.at
                                      www.traderush.com
                                      areafor.com
                                      doctsf.com
                                      kafrit.com
                                      image.gsmaweija.com
                                      istanbultarim.com.tr
                                      kuzbiqekbi.kz
                                      actfactory.net
                                      buzzkillmedia.com
                                      geothermusa.com
                                      graintrain.coop
                                      espace-hotelier.com
                                      fastarchofamerica.com
                                      fukajagalzeo.kz
                                      hitnuzufp.kz
                                      honoszihifu.kz
                                      koqfapuzfa.kz
                                      lixufeczovei.kz
                                      lognetic.com
                                      mogkogxir.kz
                                      sisogomitwu.kz
                                      sospisojo.kz
                                      tessera.co.jp
                                      isle-karnataka.org
                                      meridies.org
                                      optiver.com.au
                                      photoclubs.com
                                      re-wakefield.co.uk
                                      rixeqeklaso.kz
                                      saios.net
                                      screaminpeach.com
                                      starmedia.ca
                                      theautospas.com
                                      area72aa.org
                                      beipogitwec.kz
                                      boswuwoqru.kz
                                      boundbydesign.com
                                      caxekoqlexi.kz
                                      courtney.ca
                                      cozopoqganz.kz
                                      dimkebadka.kz
                                      dimzadcoga.kz
                                      doqxalzurm.kz
                                      doqxipuwim.kz
                                      dudajogxadbo.kz
                                      dujoduqkebos.kz
                                      eleterno.com
                                      fukebseawin.kz
                                      galhahuzri.kz
                                      gofunokurfo.kz
                                      hapogeoqedi.kz
                                      heaxelukacu.kz
                                      jiwuzgazuru.kz
                                      jogleahits.kz
                                      keqixcekvoqc.kz
                                      leacanmuz.kz
                                      leamiqedu.kz
                                      nadziwumo.kz
                                      nekzaxaddu.kz
                                      nosleaduzu.kz
                                      paldanawu.kz
                                      pikebqemuzf.kz
                                      pokurfadcogp.kz
                                      poqfadxal.kz
                                      relawoqhimur.kz
                                      seaqewisanwe.kz
                                      shipeliteexpress.com
                                      sspackaginggroup.com
                                      surgopadgo.kz
                                      surladdalc.kz
                                      teasing-video.com
                                      vadrelazuf.kz
                                      vanguardpkg.com
                                      vimhozivo.kz
                                      voswimheoj.kz
                                      wimizunudal.kz
                                      xesandadabav.kz
                                      zanwebnadr.kz
                                      zupiwoqcixdi.kz
                                      cuoxxscrhhvggevhkurnqphigp.com
                                      acmepacificrepairs.com
                                      beidiqitbad.kz
                                      calacosdijo.kz
                                      dallusiqu.kz
                                      fujino-lab.com
                                      gamblingonlinemagazine.com
                                      huseosogxima.kz
                                      mattiussiecologia.com
                                      msasys.com
                                      ompgp.co.jp
                                      qeqasufbimm.kz
                                      redconeretreat.com
                                      sun-ele.co.jp
                                      zeronet.co.jp
                                      atr-technologies.com
                                      austriansurfing.at
                                      badzuhogli.kz
                                      bapadlivubo.kz
                                      bearurbim.kz
                                      bocr.cz
                                      bromer.info
                                      bufeckebosl.kz
                                      bufjuralfa.kz
                                      buqankeladc.kz
                                      chocolatecovers.com
                                      cinoqhosufmi.kz
                                      cixlogeof.kz
                                      daheogitheo.kz
                                      dalufquseozo.kz
                                      deiqapebqede.kz
                                      dimjeamebv.kz
                                      ditsuffif.kz
                                      fadmaljar.kz
                                      fawufaqicekd.kz
                                      foshusofuj.kz
                                      goditjitdeas.kz
                                      goladnixcuha.kz
                                      gurcejodi.kz
                                      gururqebimb.kz
                                      heliomare.nl
                                      himnadfuzo.kz
                                      hinnenwiese.de
                                      hupozoslohog.kz
                                      huwadhucekru.kz
                                      jazanhujeib.kz
                                      jujibosritx.kz
                                      justconnect.co.za
                                      kaxadmomebd.kz
                                      korta-sa.com
                                      krafthaus.com
                                      ladpehoqd.kz
                                      le-mariage.com
                                      lebeadeofal.kz
                                      leroxuzkogz.kz
                                      lixkuzriqi.kz
                                      luhajuxazohi.kz
                                      lulabeorenuf.kz
                                      mitsixeaka.kz
                                      mogvoqqes.kz
                                      mogzeogit.kz
                                      muqixgitmalv.kz
                                      muzgitwecq.kz
                                      muzribosxo.kz
                                      nekdalnufq.kz
                                      nenuzoriseon.kz
                                      nori-k.com
                                      noslajixza.kz
                                      nuqevalokuzs.kz
                                      nuzifosogpu.kz
                                      paintball.be
                                      pcpeds.com
                                      pebxiranj.kz
                                      phototype.com
                                      pimalbumovu.kz
                                      poqsurwim.kz
                                      qegalfarebx.kz
                                      qidiroxeawoq.kz
                                      qosralcit.kz
                                      raljolusod.kz
                                      ranjogwum.kz
                                      ritfixboq.kz
                                      rueggeberg.com
                                      ruzdazadno.kz
                                      ruzsekcuwi.kz
                                      ryumachi-jp.com
                                      s2s.fr
                                      seaxalevubid.kz
                                      sekpuzbane.kz
                                      selldoor.pl
                                      shakeyspizza.ph
                                      shs-sales.co.uk
                                      siduxaldeiz.kz
                                      sipoheokafi.kz
                                      solutioncorp.com
                                      stepnet.de
                                      sufxolebo.kz
                                      sursicumuz.kz
                                      tenpole.com
                                      theartofhair.com
                                      unslp.edu.bo
                                      upsilon89.com
                                      vaditzurgos.kz
                                      vaxoqladcit.kz
                                      vimjizadv.kz
                                      vimqognec.kz
                                      vimsixruz.kz
                                      voqkoqsek.kz
                                      vufmiboqzu.kz
                                      vupalfosfan.kz
                                      wadqebimzi.kz
                                      wahithakurbo.kz
                                      waraxoqwoqna.kz
                                      womitwoqbac.kz
                                      woqwoqkizo.kz
                                      xadpadwebn.kz
                                      xufjoduqfu.kz
                                      youjoomla.com
                                      zacixvossur.kz
                                      zanzadcawu.kz
                                      zoveopufosri.kz
                                      zuceleiditvo.kz
                                      zufmonixl.kz
                                      zufpoxezu.kz
                                      cigeocuhogbo.kz
                                      nawanucabixv.kz
                                      nufpoqurni.kz
                                      zosheawim.kz
                                      floridadoubled.com
                                      gallazeifi.kz
                                      orion-networks.net
                                      servico-ind.com
                                      zurpimvadb.kz
                                      accel.lt
                                      al-mawared.com
                                      avant-ime.com
                                      beechwoodmetalworks.com
                                      bimoquflufpi.kz
                                      biurimex.pl
                                      boqcekusi.kz
                                      boqhavapi.kz
                                      brookfarm.com.au
                                      business-edge.com
                                      cabadhuheif.kz
                                      capitalcitytuxedo.com
                                      ceditfubeici.kz
                                      cejunudeovam.kz
                                      choice-select.com
                                      citqitsoqe.kz
                                      cixmipowo.kz
                                      cksglobal.net
                                      cosfuxoqk.kz
                                      coxaruzqufm.kz
                                      ctr4process.org
                                      cuqufmitvim.kz
                                      curmuzzozo.kz
                                      deixucuxuzbi.kz
                                      denville.ca
                                      dithd.com
                                      dubufwuzcit.kz
                                      duvadvadsar.kz
                                      eurasia.it
                                      eyggroup.com
                                      falaxehikaxe.kz
                                      fobadfasosbo.kz
                                      fopirogmalli.kz
                                      fufwuhoqk.kz
                                      fusognewubo.kz
                                      galbaqufru.kz
                                      gallipoqri.kz
                                      geamanredip.kz
                                      genmar.gen.tr
                                      gofekzurnixl.kz
                                      goodvaluecenter.com
                                      govizosfixxo.kz
                                      havukanecdac.kz
                                      heagafifecx.kz
                                      heofimjuv.kz
                                      hinupuzsomov.kz
                                      hitxalzig.kz
                                      hogfadzan.kz
                                      hufadcekwuno.kz
                                      huzredaheo.kz
                                      jansihina.kz
                                      jeagusanmovi.kz
                                      jeifimlol.kz
                                      jeiqitqab.kz
                                      jeizadihi.kz
                                      jitkallone.kz
                                      joqaxebifecp.kz
                                      joranwuzboqg.kz
                                      jubosqurqep.kz
                                      kagu-hokuren.com
                                      kalgeicufi.kz
                                      kalqurbein.kz
                                      kalwoqmiga.kz
                                      kamaruka.vic.edu.au
                                      karogralkun.kz
                                      kebxiqosc.kz
                                      konecwapimuz.kz
                                      kuzduqdeiv.kz
                                      kuzseokexu.kz
                                      lafaremunoqp.kz
                                      lanixwuqelem.kz
                                      leadershipforum.us
                                      linacurhojod.kz
                                      loqanlevoqk.kz
                                      manduqefa.kz
                                      manwafaqu.kz
                                      mastergrp-spb.ru
                                      minatech.net
                                      monofakebaq.kz
                                      muzzanduql.kz
                                      naboqbosbih.kz
                                      nadzicitw.kz
                                      nakodumulic.kz
                                      nasz-sklep.pl
                                      nazcapictures.com
                                      negithugeila.kz
                                      nocaqeqazin.kz
                                      noqqileib.kz
                                      noruzvipoqn.kz
                                      nufciqahea.kz
                                      nufxuxijix.kz
                                      padveokihi.kz
                                      palleazei.kz
                                      palmigage.kz
                                      palwumebx.kz
                                      pbna.com
                                      pemebranfos.kz
                                      plus.ba
                                      poqsokebm.kz
                                      puzwuvuzn.kz
                                      qekkipalj.kz
                                      qelibadcakej.kz
                                      qimeblocosqu.kz
                                      qurxelanna.kz
                                      ralremogum.kz
                                      rexisixjitf.kz
                                      ritfixdal.kz
                                      rogmileix.kz
                                      ropebsogwecd.kz
                                      rurxohimf.kz
                                      ruzcucurze.kz
                                      ruznossixn.kz
                                      sanmurmeaq.kz
                                      sarpy.com
                                      seohiqekiwa.kz
                                      sogmohogfa.kz
                                      thedonaldsongroup.com
                                      theprintinghouseltd.co.uk
                                      totalearthcare.com.au
                                      unitedearthgroup.com
                                      viwaljixjaqi.kz
                                      vobahogsisos.kz
                                      weclavimsi.kz
                                      weczipimje.kz
                                      wkhk.net
                                      xeaqazanga.kz
                                      xebokoqjith.kz
                                      xicogvosrob.kz
                                      xipimxexigal.kz
                                      xonosveomanj.kz
                                      yamamoto-sr.com
                                      zangalbadg.kz
                                      zohabafekne.kz
                                      zosxezurx.kz
                                      zunemebxefix.kz
                                      zurhiqewec.kz
                                      fecmogbeo.kz
                                      fekloraref.kz
                                      kapexacosbap.kz
                                      perc.ca
                                      qandumebbi.kz
                                      zadvoqkuw.kz
                                      leabixdei.kz
                                      sursurdalp.kz
                                      acsmedioambiente.com
                                      agrarno.ru
                                      badrogcape.kz
                                      beizurlango.kz
                                      beobimrebbos.kz
                                      bixbadloli.kz
                                      bolodimhifa.kz
                                      bosgeosibe.kz
                                      camoxobeaji.kz
                                      cekveidoq.kz
                                      cgc-england.com
                                      chscreative.com
                                      cixfarogq.kz
                                      cixhitzug.kz
                                      cocoszeihoq.kz
                                      cozannimqav.kz
                                      curxeacabu.kz
                                      dabixcekkaw.kz
                                      dalgajitb.kz
                                      danufditgimu.kz
                                      digpro.se
                                      dimwisasof.kz
                                      duqlibadpe.kz
                                      fimfuruzx.kz
                                      fipechabeim.kz
                                      fixbozokal.kz
                                      fixwecpeno.kz
                                      fonodifanaw.kz
                                      fuhamebcitne.kz
                                      gaheobanufmo.kz
                                      galhoqjoqi.kz
                                      ganwoqvei.kz
                                      gcs-cpa.com
                                      geilafapo.kz
                                      gopoqnuqann.kz
                                      hapalxuzdit.kz
                                      hogvugeoc.kz
                                      holemomohog.kz
                                      huhaxoqlixz.kz
                                      huhixadfudi.kz
                                      hunozeoxeaqa.kz
                                      huzlufseop.kz
                                      janbadluf.kz
                                      jeangatz.com
                                      jeonimvufv.kz
                                      jimiviqucax.kz
                                      jirancicusa.kz
                                      jobosxealad.kz
                                      kabifipalfu.kz
                                      kacixcosnoj.kz
                                      kalhoheopi.kz
                                      kaxijanvavu.kz
                                      kenobosbosd.kz
                                      kiroglicefek.kz
                                      kizolowuladq.kz
                                      koqfekkurd.kz
                                      kurbosdoq.kz
                                      ladgeasea.kz
                                      ladzafuco.kz
                                      leacubufv.kz
                                      leaqosrix.kz
                                      liconoqwoxuw.kz
                                      losurdunufga.kz
                                      lufrikewo.kz
                                      nadzanfix.kz
                                      nekgacanja.kz
                                      nekjeosurd.kz
                                      nekveogeal.kz
                                      nimkunuli.kz
                                      nixlawimhi.kz
                                      noxepikurco.kz
                                      nufhitnuna.kz
                                      palkaduqd.kz
                                      peclearalc.kz
                                      pejeazasufc.kz
                                      pidoqzofufd.kz
                                      pinimriwebx.kz
                                      pogohoglixlo.kz
                                      puzkanoqg.kz
                                      puzzanrej.kz
                                      qahawomuzufb.kz
                                      qeguhanunim.kz
                                      qeksinosg.kz
                                      qitbeilein.kz
                                      qitqufquju.kz
                                      qoswebgei.kz
                                      racknstackwarehouse.com.au
                                      ranpalnun.kz
                                      realtechre.com
                                      rebzomeaji.kz
                                      regazoxagit.kz
                                      rifeckogweb.kz
                                      rimiceladbuf.kz
                                      sancuxanos.kz
                                      sarahdavid.com
                                      sekmonufxo.kz
                                      sobufagurjod.kz
                                      sosjogfir.kz
                                      sztartufi.com
                                      taykon.com
                                      trinity-works.com
                                      viqitjeaqix.kz
                                      vitalur.by
                                      voqsandoq.kz
                                      voqxahamu.kz
                                      voqzankuz.kz
                                      voszufvazu.kz
                                      wadriwuwuz.kz
                                      wibadjihawo.kz
                                      wimmalzone.kz
                                      wohagurguhea.kz
                                      x-cellcommunications.de
                                      xadgaritji.kz
                                      xegeibeanimq.kz
                                      xehiricoshe.kz
                                      xemozageaqa.kz
                                      xeroggeoleqi.kz
                                      xikuzlixvuf.kz
                                      xipobapodalg.kz
                                      xoqguqekd.kz
                                      xuanxiao.com
                                      zabufrafazu.kz
                                      zansurmurq.kz
                                      zanzeiheor.kz
                                      zossosmal.kz
                                      zoxomuzjuzad.kz
                                      zufokujogmuz.kz
                                      appelfarm.org
                                      beipoganbuf.kz
                                      bixzoziruz.kz
                                      cansealuf.kz
                                      didahogqeco.kz
                                      duqjeadeac.kz
                                      fecbosxoq.kz
                                      fecmomalq.kz
                                      focuxojixna.kz
                                      foskebmalc.kz
                                      fulufhuzvade.kz
                                      fuzadzageixe.kz
                                      ganmuzmal.kz
                                      gucarogmitq.kz
                                      hitcosxiq.kz
                                      hujonixbanos.kz
                                      icigrain.com
                                      iktus.fr
                                      kemurgupuzqu.kz
                                      nadveihea.kz
                                      noheijeaweb.kz
                                      pebhomogd.kz
                                      peheiveoveo.kz
                                      poveixufbuba.kz
                                      puzfuffix.kz
                                      qipadxoqqogs.kz
                                      rafajeiwuzz.kz
                                      rakebveizip.kz
                                      rankanufb.kz
                                      rexufwidapa.kz
                                      rilepecrogq.kz
                                      vimdafaho.kz
                                      voswimfozo.kz
                                      vuzcekquj.kz
                                      vuzvuzsog.kz
                                      waqixwoqkaln.kz
                                      woqvocujuq.kz
                                      worapadsicux.kz
                                      xeagitjeir.kz
                                      xoqqekzuf.kz
                                      zeifabadce.kz
                                      adultlivechat.us
                                      arckepesajandek.hu
                                      asj.co.jp
                                      bamiripulovi.kz
                                      beageapus.kz
                                      bixsurxecu.kz
                                      borikomitba.kz
                                      cekdeabos.kz
                                      cogfecsufq.kz
                                      curminecva.kz
                                      cururgeajali.kz
                                      dithasixv.kz
                                      fanadlafufwu.kz
                                      fixvanavad.kz
                                      ganxenekr.kz
                                      gimaljixwal.kz
                                      graceweb.net
                                      heixearebmit.kz
                                      jajitwecfox.kz
                                      jareqiqurxu.kz
                                      jeifoxeso.kz
                                      kalopecvakab.kz
                                      lewazubimgo.kz
                                      lixmurbeom.kz
                                      lobimkebkalq.kz
                                      munekdalpalw.kz
                                      nadjeicix.kz
                                      nufkitsurs.kz
                                      nuqurwoqqufa.kz
                                      pebeodawoha.kz
                                      pecbapiqos.kz
                                      pelipolidub.kz
                                      pivaqoglads.kz
                                      piwowiduduxo.kz
                                      pixoqheowir.kz
                                      pusixpadlanq.kz
                                      puzfoxiju.kz
                                      rodeoshow.com.au
                                      seoduqheipa.kz
                                      soshitfix.kz
                                      toddpipe.com
                                      victoria.com.pl
                                      voqzuseoc.kz
                                      wecnadmalk.kz
                                      wozonufjala.kz
                                      wuvicimoxax.kz
                                      xaddeowebp.kz
                                      xofecsixdeoz.kz
                                      xuzbealis.kz
                                      zacixboqpec.kz
                                      zufzufquf.kz
                                      badfonamow.kz
                                      badfovosqi.kz
                                      badvimmura.kz
                                      bimxobixn.kz
                                      boxifovosxa.kz
                                      brijindia.com
                                      cajorazufwe.kz
                                      caqivoqmoxuz.kz
                                      cbsprinting.com.au
                                      cekfixriv.kz
                                      cekfobeov.kz
                                      cekjoglad.kz
                                      celebikalip.com.tr
                                      cixguqiru.kz
                                      cogkezufdi.kz
                                      coleilopiqu.kz
                                      colourprint.nl
                                      cosnaqasu.kz
                                      dalheokeb.kz
                                      deopirogd.kz
                                      fixhapebxa.kz
                                      fixqurlanr.kz
                                      fofonoqperir.kz
                                      fojognucuqa.kz
                                      fuzeicekheam.kz
                                      geageobiqit.kz
                                      giqixjocife.kz
                                      gurimalxabub.kz
                                      gurmebxad.kz
                                      heacepinadv.kz
                                      heahocogwub.kz
                                      iaiglobal.or.id
                                      jajaseowubo.kz
                                      jitnesajan.kz
                                      jopebkitboqs.kz
                                      kebdeizuf.kz
                                      koqreqanbu.kz
                                      kuzralbeip.kz
                                      labafufpoluq.kz
                                      ladzujili.kz
                                      leixizuxuz.kz
                                      lufheagan.kz
                                      mebcixcekk.kz
                                      mebpobeozo.kz
                                      mebxufqurl.kz
                                      mugujolovadv.kz
                                      peccirogwi.kz
                                      pesannoqboq.kz
                                      pezosdirehe.kz
                                      qogziziguq.kz
                                      qosfixvip.kz
                                      qufpokoqx.kz
                                      quhimxugeag.kz
                                      ranpovine.kz
                                      regukilomic.kz
                                      seopoqcurna.kz
                                      sixzaline.kz
                                      tutuji-saitama.com
                                      vufjoguwim.kz
                                      wadqogruzh.kz
                                      wadsinoqba.kz
                                      walbeakuz.kz
                                      weczorurso.kz
                                      xadmitgigi.kz
                                      xadzopoqle.kz
                                      zadligida.kz
                                      zanxadmuje.kz
                                      zileicanwec.kz
                                      zofupebgozos.kz
                                      zosnubimr.kz
                                      bufkurhitf.kz
                                      bufxoxoqfa.kz
                                      cofosfimran.kz
                                      data-center.co
                                      deaqagucit.kz
                                      difacogxufp.kz
                                      dunavikalanj.kz
                                      faxicitkadei.kz
                                      fisogxoqker.kz
                                      fixqitnoqz.kz
                                      fruitspot.co.za
                                      fufsurveo.kz
                                      fuvosmurdimg.kz
                                      geagiwimxiw.kz
                                      geolicojei.kz
                                      heafojuhamu.kz
                                      hoqfimburi.kz
                                      hoqseafohu.kz
                                      ixtractor.com
                                      jeimitzei.kz
                                      jixgijitl.kz
                                      jixheibuf.kz
                                      jixrurfix.kz
                                      jozufxuzfol.kz
                                      jumikapeczos.kz
                                      juqafufgeaga.kz
                                      kemalkaljuwa.kz
                                      kurnekhim.kz
                                      ladpokamo.kz
                                      lanpecruzk.kz
                                      leavadpal.kz
                                      likuzralmov.kz
                                      manrepoqm.kz
                                      mocafipalle.kz
                                      mohazadjanwe.kz
                                      mulijeojeare.kz
                                      noskazohei.kz
                                      nufquvogei.kz
                                      pevuzannimz.kz
                                      popejeasive.kz
                                      qogjafecda.kz
                                      quflufcuh.kz
                                      relosogqurhu.kz
                                      rogbixabo.kz
                                      rogxalmuz.kz
                                      ruznufqehu.kz
                                      sanoskovosl.kz
                                      seoreceladm.kz
                                      vadfozadvu.kz
                                      vaqosnimpal.kz
                                      vohuzwuladhe.kz
                                      voqxufaxo.kz
                                      vuzgeowad.kz
                                      wazufdimvape.kz
                                      wonufsogdea.kz
                                      wuzhuxujo.kz
                                      xojixpodimgu.kz
                                      xoqfekzoz.kz
                                      xoqzihuri.kz
                                      zavawimziba.kz
                                      zosdimpec.kz
                                      zufjinosc.kz 
                                ))
    end

    it 'places all the IPs in an array inside @ips' do
      expect(@obj.ips).to(
        match_array(%w(186.159.1.217 186.10.243.70).map {|i| IPAddr.new i})
      )
    end
  end
end
